services:
  - type: web
    name: financial-dashboard
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENDART_API_KEY
        sync: 51a6323f6aafba68f6a1263c140043b5d3d42175

